#!/usr/bin/env bash

# Runs the game. Usage:
#
#   ./run       # debug mode, with OpenGL error checking
#   ./run -O    # debug off, significantly faster.

ve="$HOME/.virtualenvs/belter"
python="${ve}/bin/python"
${python} $@ -c "from belter.main import main ; main()"

