#!/usr/bin/env python3

# Runs the game. Usage:
#
#   ./run           # debug mode, with OpenGL error checking
#
#   python -O run   # debug off, significantly faster.

from belter.main import main
main()

